addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.21")
addSbtPlugin("com.github.sbt" % "sbt-pgp"      % "2.1.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt" % "2.5.1")
addSbtPlugin("com.github.sbt" % "sbt-release"  % "1.1.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"     % "2.3.7")
addSbtPlugin("com.github.sbt" % "sbt-git"      % "2.0.1")
