addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"      % "2.3.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"     % "2.6.2")
addSbtPlugin("com.github.sbt" % "sbt-release"  % "1.4.0")
addSbtPlugin("com.github.sbt" % "sbt-git"      % "2.1.0")
addSbtPlugin("com.github.sbt" % "sbt-protobuf" % "0.8.1")
